#This program reads two files generated by write-xy.f95 and plots the values using matplotlib

import matplotlib.pyplot as plt

#open "x_values.txt" and retreive values
x_file = open('x_values.txt')
x_values = x_file.readlines()
x_file.close()

#open "y_values.txt" and retrieve values 
y_file = open('y_values.txt')
y_values = y_file.readlines()
y_file.close

#trim values, convert values from string to float
for i in range(len(x_values)):
    x_values[i] = float(x_values[i].strip())

for i in range(len(y_values)):
    y_values[i] = float(y_values[i].strip())
    
plt.plot(x_values,y_values)
plt.show()
